<div>
    @if($showCreate)
        <x-jobs.create
            :client-filter-options="$clientFilterOptions"
            :owner-filter-options="$ownerFilterOptions"
            :workflow-filter-options="$workflowFilterOptions"
            :category-filter-options="$categoryFilterOptions"
            :clients="$clients"
            :workflows="$workflows"
            :categories="$categories"
            :priorities="$priorities"
            :mention-users="$mentionUsers"
            :client-id="$clientId"
            :workflow-id="$workflowId"
            :owner-id="$ownerId"
            :job-items="$jobItems"
            :job-attachments="$jobAttachments"
            :catalog-ready="$createCatalogReady"
            :assignment-ready="$createAssignmentReady"
            :workflow-ready="$createWorkflowReady"
            wire:key="job-create"
        />
    @elseif($selectedTask)
        <x-jobs.task-detail
            :task="$selectedTask"
            :mention-users="$mentionUsers"
            :task-progress="$taskProgress"
            :task-statuses="$taskStatuses"
            :priorities="$priorities"
            :available-documents="$availableDocuments"
            :activity-tab="$taskActivityTab"
            :activity-page="$taskActivityPage"
            :task-document-uploads="$taskDocumentUploads"
            :show-task-document-picker="$showTaskDocumentPicker"
            :edit-mode="$taskEditMode"
            wire:key="task-detail-{{ $selectedTask->id }}-{{ $taskEditMode ? 'edit' : 'view' }}"
        />
    @elseif($selectedJob)
        <x-jobs.detail
            :job="$selectedJob"
            :detail-tab="$detailTab"
            :expanded-phase-ids="$expandedPhaseIds"
            :task-statuses="$taskStatuses"
            :users="$users"
            :mention-users="$mentionUsers"
            :priorities="$priorities"
            :products="$products"
            :categories="$categories"
            :available-documents="$availableDocuments"
            :health-options="$healthOptions"
            :job-task-search="$jobTaskSearch"
            :activity-tab="$jobActivityTab"
            :activity-page="$jobActivityPage"
            :job-document-uploads="$jobDocumentUploads"
            :show-document-picker="$showDocumentPicker"
            wire:key="job-detail-{{ $selectedJob->id }}"
        />
    @else
        <x-jobs.table
            :jobs="$jobs"
            :search-filter="$search"
            wire:key="orders-list"
        />
    @endif
</div>
