<div>
    @if($showCreate)
        <x-jobs.create
            :clients="$clients"
            :workflows="$workflows"
            :users="$users"
            :categories="$categories"
            :products="$products"
            :priorities="$priorities"
            :mention-users="$mentionUsers"
            :client-id="$clientId"
            :workflow-id="$workflowId"
            :job-items="$jobItems"
            :job-attachments="$jobAttachments"
            :catalog-ready="$createCatalogReady"
            :assignment-ready="$createAssignmentReady"
            :workflow-ready="$createWorkflowReady"
            wire:key="job-create"
        />
    @elseif($selectedTask)
        <x-jobs.task-detail
            :task="$selectedTask"
            :users="$users"
            :mention-users="$mentionUsers"
            :task-progress="$taskProgress"
            :task-statuses="$taskStatuses"
            :priorities="$priorities"
            :available-documents="$availableDocuments"
            :activity-tab="$taskActivityTab"
            :activity-page="$taskActivityPage"
            :task-document-uploads="$taskDocumentUploads"
            :show-task-document-picker="$showTaskDocumentPicker"
            wire:key="task-detail-{{ $selectedTask->id }}"
        />
    @elseif($selectedJob)
        <x-jobs.detail
            :job="$selectedJob"
            :detail-tab="$detailTab"
            :expanded-phase-ids="$expandedPhaseIds"
            :task-statuses="$taskStatuses"
            :users="$users"
            :mention-users="$mentionUsers"
            :priorities="$priorities"
            :products="$products"
            :categories="$categories"
            :available-documents="$availableDocuments"
            :health-options="$healthOptions"
            :job-task-search="$jobTaskSearch"
            :activity-tab="$jobActivityTab"
            :activity-page="$jobActivityPage"
            :job-document-uploads="$jobDocumentUploads"
            :show-document-picker="$showDocumentPicker"
            wire:key="job-detail-{{ $selectedJob->id }}"
        />
    @else
        <x-jobs.table
            :jobs="$jobs"
            :job-summary="$jobSummary"
            :clients="$clients"
            :phases="$phases"
            :users="$users"
            :priorities="$priorities"
            :health-options="$healthOptions"
            :job-statuses="$jobStatuses"
            :phase-filter="$phase"
            :health-filter="$health"
            :quick-filter="$quickFilter"
            :show-more-filters="$showMoreFilters"
            :selected-job-ids="$selectedJobIds"
            :all-filtered-jobs-selected="$allFilteredJobsSelected"
            wire:key="jobs-table"
        />
    @endif
</div>
