<div>
    @if($showCreate)
        <x-jobs.create :clients="$clients" :workflows="$workflows" :users="$users" :categories="$categories" :products="$products" :priorities="$priorities" :client-id="$clientId" :workflow-id="$workflowId" :job-items="$jobItems" :job-attachments="$jobAttachments" />
    @elseif($selectedTask)
        <x-jobs.task-detail
            :task="$selectedTask"
            :users="$users"
            :task-progress="$taskProgress"
            :task-statuses="$taskStatuses"
            :priorities="$priorities"
            :available-documents="$availableDocuments"
            :activity-tab="$taskActivityTab"
            :activity-page="$taskActivityPage"
            :task-document-uploads="$taskDocumentUploads"
            :show-task-document-picker="$showTaskDocumentPicker"
        />
    @elseif($selectedJob)
        <x-jobs.detail
            :job="$selectedJob"
            :detail-tab="$detailTab"
            :expanded-phase-ids="$expandedPhaseIds"
            :task-statuses="$taskStatuses"
            :users="$users"
            :priorities="$priorities"
            :products="$products"
            :categories="$categories"
            :available-documents="$availableDocuments"
            :health-options="$healthOptions"
            :job-task-search="$jobTaskSearch"
            :activity-tab="$jobActivityTab"
            :activity-page="$jobActivityPage"
            :job-document-uploads="$jobDocumentUploads"
            :show-document-picker="$showDocumentPicker"
        />
    @else
        <span class="ft-jobs-list-poll" aria-hidden="true"></span>
        <x-jobs.table
            :jobs="$jobs"
            :job-summary="$jobSummary"
            :clients="$clients"
            :phases="$phases"
            :users="$users"
            :priorities="$priorities"
            :health-options="$healthOptions"
            :job-statuses="$jobStatuses"
            :phase-filter="$phase"
            :health-filter="$health"
            :quick-filter="$quickFilter"
            :show-more-filters="$showMoreFilters"
            :selected-job-ids="$selectedJobIds"
            :all-filtered-jobs-selected="$allFilteredJobsSelected"
        />
    @endif
</div>
