@props(['users','clientCode'])
<div class="ft-create-client-page">
    <div class="ft-client-create-shell">
        <div class="ft-client-create-top">
            <div><div class="ft-create-breadcrumb">Add Client</div><h1>Add Client</h1><p>Client information is saved as a full page, not a drawer.</p></div>
            <button type="button" class="ft-back-clients" wire:click="closeCreate">← Back to Clients</button>
        </div>

        <section class="ft-client-form-card">
            <div class="ft-client-form-head"><h2>Create New Client</h2><p>Client details are shared across Orders, documents and reporting.</p></div>
            <div class="ft-client-form-body">
                <label class="ft-client-field"><b>Client code</b><div class="ft-client-code-box">{{ $clientCode }}</div><small>🔒 &nbsp; Automatically generated by FlowTrack and permanently locked.</small></label>
                <label class="ft-client-field"><b>Client name *</b><input wire:model="clientName" placeholder="Company or organisation name">@error('clientName')<small class="validation-error">{{ $message }}</small>@enderror</label>
                <label class="ft-client-field"><b>Country</b><input wire:model="clientCountry" placeholder="e.g. United States"></label>
                <label class="ft-client-field"><b>Office address</b><input wire:model="officeAddress" placeholder="Office / mailing address"></label>
                <label class="ft-client-field"><b>Primary contact</b><input wire:model="contactName" placeholder="Contact person"></label>
                <label class="ft-client-field"><b>Email</b><input type="email" wire:model="email" placeholder="contact@company.com">@error('email')<small class="validation-error">{{ $message }}</small>@enderror</label>
                <label class="ft-client-field"><b>Phone</b><input wire:model="phone" placeholder="Phone number"></label>
                <label class="ft-client-field"><b>Account manager</b><select wire:model="accountManagerId"><option value="">Unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select></label>
                <label class="ft-client-field"><b>Preferred language</b><select wire:model="preferredLanguage"><option>English</option><option>Chinese</option><option>Spanish</option><option>French</option><option>German</option><option>Arabic</option><option>Bengali</option></select></label>
                <label class="ft-client-field"><b>Outstanding balance</b><input type="number" step="0.01" min="0" wire:model="outstandingBalance">@error('outstandingBalance')<small class="validation-error">{{ $message }}</small>@enderror</label>
                <label class="ft-client-field"><b>Notes</b><textarea rows="4" wire:model="notes" placeholder="Commercial notes, preferences or account instructions..."></textarea></label>
            </div>
            <div class="ft-client-form-actions"><button type="button" class="ft-create-cancel" wire:click="closeCreate">Cancel</button><button type="button" class="ft-create-primary" wire:click="createClient">Create Client</button></div>
        </section>
    </div>
</div>
